### ISSUE TITLE
[catalog] No description of License field

### ISSUE THREAD

**Issue by funnelfiasco** [ossf/sbom-everywhere#64]
The SBOM Catalog's [contributing docs](https://github.com/ossf/sbom-everywhere/tree/main/SBOM-Catalog/contribute.md) don't mention the *License* field that appears in data.yaml.

**Comment by funnelfiasco** [comment]
I am working on a PR for this

**Comment by Mariuxdeangelo** [comment]
Thanks for your contributions @funnelfiasco. It's great having you. For the time being, I just used the license field to distinguish between open-source and proprietary products. But please feel free to make any other suggestions. I hope to find some time for this project again soon. 

Also, I've not written something in regard to the language field. The issue here is that there are overlapping data points that can be hard to figure out. E.g. Java`, `Kotlin`, `Scala` can work with `Maven` or `Gradle`. So each of these words could be synonyms... or not. Depending on the App evaluated 😅
